version: 7
profiles:
  - type: local
    name: localhost
    icon: fas fa-terminal
    options:
      command: /bin/bash
      args:
        - '-l'
      env: {}
      cwd: ''
    group: fc8c2205-0914-451e-b361-b5fe621ca764
    id: local:custom:bash:48718384-fdd9-4d85-87d1-8640970968d0
    color: '#00FF00'
  - name: NAS
    icon: fas fa-server
    options:
      host: nas.lan
      algorithms:
        hmac:
          - hmac-sha2-512
        kex:
          - curve25519-sha256
        cipher:
          - aes256-gcm@openssh.com
        serverHostKey:
          - rsa-sha2-512
      input: {}
      keepaliveCountMax: 100000
      privateKeys: []
      forwardedPorts: []
      scripts: []
    weight: -1
    group: fc8c2205-0914-451e-b361-b5fe621ca764
    id: ssh:custom:NAS:da9216f8-2e34-4465-8e5f-48b480d9acac
    color: '#FF0000'
    type: ssh
groups:
  - id: fc8c2205-0914-451e-b361-b5fe621ca764
    name: Default
configSync:
  parts: {}
hotkeys:
  toggle-window:
    - Ctrl-Space
  copy-current-path:
    - Ctrl-P
  ctrl-c:
    - Ctrl-C
  copy:
    - Ctrl-Shift-C
  paste:
    - Ctrl-Shift-V
    - Shift-Insert
  select-all:
    - Ctrl-Shift-A
  clear: []
  zoom-in:
    - Ctrl-=
    - Ctrl-Shift-=
  zoom-out:
    - Ctrl--
    - Ctrl-Shift--
  reset-zoom:
    - Ctrl-0
  home:
    - Home
  end:
    - End
  previous-word:
    - Ctrl-Left
  next-word:
    - Ctrl-Right
  delete-previous-word:
    - Ctrl-Backspace
  delete-next-word:
    - Ctrl-Delete
  search:
    - Ctrl-Shift-F
  pane-focus-all:
    - Ctrl-Shift-I
  focus-all-tabs:
    - Ctrl-Alt-Shift-I
  scroll-to-top:
    - Ctrl-PageUp
    - Ctrl-Alt-Up
  scroll-to-bottom:
    - Ctrl-PageDown
    - Ctrl-Alt-Down
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings-tab: {}
  settings:
    - Ctrl-,
  serial:
    - Alt-K
  restart-serial-session: []
  new-tab:
    - Ctrl-Shift-T
  new-window:
    - Ctrl-Shift-N
  profile:
    ssh:custom:NAS:da9216f8-2e34-4465-8e5f-48b480d9acac:
      - Ctrl-Alt-Shift-N
  profile-selectors: {}
  toggle-fullscreen:
    - F11
  close-tab:
    - Ctrl-Shift-W
  reopen-tab:
    - Ctrl-Shift-Z
  toggle-last-tab: []
  rename-tab:
    - Ctrl-Shift-R
  next-tab:
    - Ctrl-Shift-Right
    - Ctrl-Tab
  previous-tab:
    - Ctrl-Shift-Left
    - Ctrl-Shift-Tab
  move-tab-left:
    - Ctrl-Shift-PageUp
  move-tab-right:
    - Ctrl-Shift-PageDown
  rearrange-panes:
    - Ctrl-Shift
  duplicate-tab: []
  restart-tab: []
  reconnect-tab: []
  disconnect-tab: []
  explode-tab:
    - Ctrl-Shift-.
  combine-tabs:
    - Ctrl-Shift-,
  tab-1:
    - Alt-1
  tab-2:
    - Alt-2
  tab-3:
    - Alt-3
  tab-4:
    - Alt-4
  tab-5:
    - Alt-5
  tab-6:
    - Alt-6
  tab-7:
    - Alt-7
  tab-8:
    - Alt-8
  tab-9:
    - Alt-9
  tab-10:
    - Alt-0
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - Ctrl-Shift-S
  split-bottom:
    - Ctrl-Shift-D
  split-left: []
  split-top: []
  pane-nav-right:
    - Alt-Right
  pane-nav-down:
    - Alt-Down
  pane-nav-up:
    - Alt-Up
  pane-nav-left:
    - Alt-Left
  pane-nav-previous:
    - Ctrl-Alt-[
  pane-nav-next:
    - Ctrl-Alt-]
  pane-nav-1: []
  pane-nav-2: []
  pane-nav-3: []
  pane-nav-4: []
  pane-nav-5: []
  pane-nav-6: []
  pane-nav-7: []
  pane-nav-8: []
  pane-nav-9: []
  pane-maximize:
    - Ctrl-Alt-Enter
  pane-increase-vertical: []
  pane-decrease-vertical: []
  pane-increase-horizontal: []
  pane-decrease-horizontal: []
  close-pane: []
  switch-profile:
    - Ctrl-Alt-T
  profile-selector:
    - Ctrl-Shift-E
  command-selector:
    - Ctrl-Shift-P
  delete-line:
    - Ctrl-K
    - Ctrl-Shift-Backspace
  scroll-up:
    - Alt-PageUp
    - Ctrl-Up
  scroll-down:
    - Alt-PageDown
    - Ctrl-Down
terminal:
  searchOptions: {}
  colorScheme:
    name: Trihedraf
    foreground: '#f2f2f2'
    background: '#0D0D0D'
    cursor: '#FFFFFF'
    colors:
      - '#000000'
      - '#990000'
      - '#00a600'
      - '#999900'
      - '#2009db'
      - '#b200b2'
      - '#00a6b2'
      - '#bfbfbf'
      - '#666666'
      - '#e50000'
      - '#00d900'
      - '#e5e500'
      - '#0000ff'
      - '#e500e5'
      - '#00e5e5'
      - '#e5e5e5'
    cursorAccent: ''
    selection: '#666666'
    selectionForeground: ''
  font: Source Code Pro
  cursor: underline
  fallbackFont: Ubuntu Mono
  profile: local:custom:bash:48718384-fdd9-4d85-87d1-8640970968d0
  showRecentProfiles: 0
  customColorSchemes:
    - name: Trihedraf
      foreground: '#f2f2f2'
      background: '#0D0D0D'
      cursor: '#FFFFFF'
      colors:
        - '#000000'
        - '#990000'
        - '#00a600'
        - '#999900'
        - '#2009db'
        - '#b200b2'
        - '#00a6b2'
        - '#bfbfbf'
        - '#666666'
        - '#e50000'
        - '#00d900'
        - '#e5e500'
        - '#0000ff'
        - '#e500e5'
        - '#00e5e5'
        - '#e5e5e5'
      cursorAccent: ''
      selection: '#666666'
      selectionForeground: ''
  frontend: xterm
  scrollbackLines: 100000
  pasteOnMiddleClick: true
  bell: visual
  showTabProfileIcon: true
  altIsMeta: true
  lightColorScheme:
    name: Trihedraf
    foreground: '#f2f2f2'
    background: '#0D0D0D'
    cursor: '#FFFFFF'
    colors:
      - '#000000'
      - '#990000'
      - '#00a600'
      - '#999900'
      - '#2009db'
      - '#b200b2'
      - '#00a6b2'
      - '#bfbfbf'
      - '#666666'
      - '#e50000'
      - '#00d900'
      - '#e5e500'
      - '#0000ff'
      - '#e500e5'
      - '#00e5e5'
      - '#e5e5e5'
    cursorAccent: ''
    selection: '#666666'
    selectionForeground: ''
clickableLinks:
  modifier: ctrlKey
accessibility: {}
appearance:
  colorSchemeMode: auto
  tabsLocation: left
  tabsInFullscreen: true
hacks: {}
providerBlacklist: []
commandBlacklist: []
enableAnalytics: false
enableWelcomeTab: false
pluginBlacklist:
  - community-color-schemes
  - serial
profileDefaults:
  local:
    type: local
    color: '#00FF00'
  ssh:
    disableDynamicTitle: true
    type: ssh
    color: '#FF0000'
profileBlacklist: []
